### ISSUE TITLE
Feature Request: Timer color scheme toggle

### ISSUE THREAD

**Issue by timkite** [diejmon/BillingTimer-Support#8]
I just want to say I love the app. Super simple and perfect for my needs.

I noticed on my laptop (2015 MBP 13" Retina), even though the system appearance is set to "Blue", I get the monochrome colors in Billing Timer (which might be a bug, but is a fortunate one since I prefer the monochrome look). On my iMac at work, also with appearance set to "Blue", I get red/yellow/green colors depending on timer state. Toggling the iMac to Graphite gives me the monochrome timer appearance.

What I'm wondering if the timer appearance could be tied to a toggle in the app settings instead of the system appearance? I also run NagBar, so seeing colors in my menu bar usually means the status of a server is changing, and would prefer to have BillingTimer be fully monochrome regardless of the system color scheme. Thanks!

**Comment by diejmon** [comment]
Hi Tim, thanks for feedback, this feature has been implemented and will be released with next version in about a month.
