### ISSUE TITLE
Text Contrast in Dark Mode in Mojave

### ISSUE THREAD

**Issue by timkite** [diejmon/BillingTimer-Support#9]
The billing timer app's background and button glyphs automatically transition to dark mode in Mojave! However, the text on the timers themselves stays black, so it's black text on a dark grey background. It's readable, but only just. Could the contrast be improved in a future release, maybe using white text when in dark mode?

**Comment by timkite** [comment]
I didn't realize you could attach pictures in these, and that might be helpful. Here's a couple of screenshots showing light mode vs. dark mode in Mojave for Billing Timer.
<img width="392" alt="dark-mode" src="https://user-images.githubusercontent.com/6933976/46503966-7d230a80-c7fa-11e8-9df1-8ba0e17d96b0.png">
<img width="392" alt="light-mode" src="https://user-images.githubusercontent.com/6933976/46503967-7d230a80-c7fa-11e8-843b-39b91be4ec95.png">

I'm not sure, but the easiest fix might be to make the timer backgrounds always be white. That way it works on pre-10.14 "dark menu bar and dock" as well as post-10.14 "dark everything".

**Comment by diejmon** [comment]
Dark Mode on a the way, thanks for report!
